#################################################
# Base configuration
#################################################



#################################################
# Platforms to test
#################################################


include:
  - '.gitlab-ci-files/job-android.yml'
  - '.gitlab-ci-files/job-windows.yml'

stages:
 - build
