.job-android:

  stage: build
  tags: [ "docker-android" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-android/bc-dev-android:30

job-android-hello-world:
  extends: .job-android
  script:
    - cd android/kotlin/0-HelloWorld/
    - ./gradlew assembleRelease

job-android-account:
  extends: .job-android
  script:
    - cd android/kotlin/1-AccountLogin/
    - ./gradlew assembleRelease

job-android-push-notifications:
  extends: .job-android
  script:
    - cd android/kotlin/2-PushNotifications/
    - ./gradlew assembleRelease

job-android-basic-chat:
  extends: .job-android
  script:
    - cd android/kotlin/5-BasicChat/
    - ./gradlew assembleRelease

job-android-advanced-chat:
  extends: .job-android
  script:
    - cd android/kotlin/6-AdvancedChat/
    - ./gradlew assembleRelease

job-android-incoming-call:
  extends: .job-android
  script:
    - cd android/kotlin/3-IncomingCall/
    - ./gradlew assembleRelease

job-android-outgoing-call:
  extends: .job-android
  script:
    - cd android/kotlin/4-OutgoingCall/
    - ./gradlew assembleRelease